ruby/vota_prato/config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :restaurantes

  resources :qualificacoes

  resources :clientes

   match 'rack', :to => proc{|env|[200,{"Content-Type" => "text/html"},["App Rack numa rota Rails"]]}	
   match ':controller(/:action(/:id(.:format)))'
end

ruby/vota_prato/app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  # GET /qualificacoes
  # GET /qualificacoes.xml
  def index
    @qualificacoes = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.xml
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.xml
  def new
    @qualificacao = Qualificacao.new

	if params[:cliente]
	  @qualificacao.cliente = Cliente.find(params[:cliente])
	end
	if params[:restaurante]
	  @qualificacao.restaurante = Restaurante.find(params[:restaurante])
	end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @qualificacao }
    end

  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.xml
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully created.') }
        format.xml  { render :xml => @qualificacao, :status => :created, :location => @qualificacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.xml
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.xml
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to(qualificacoes_url) }
      format.xml  { head :ok }
    end
  end
end

ruby/vota_prato/app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

ruby/vota_prato/app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<% if @qualificacao.cliente %>
	  <%= f.hidden_field "cliente_id" %>
	<% else %>
	  <p><%= f.label :cliente_id %><br />
	  <%= f.collection_select(:cliente_id,
		  Cliente.order("nome"),
		  :id, :nome, {:prompt => true}) %></p>
	<% end %>

  </div>
  <div class="field">
	<% if @qualificacao.restaurante %>
	  <%= f.hidden_field "restaurante_id" %>
	<% else %>
	  <p><%= f.label :restaurante_id %><br />
	  <%= f.collection_select(:restaurante_id,
		  Restaurante.order("nome"),
		  :id, :nome, {:prompt => true}) %></p>
	<% end %>

  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/vota_prato/app/views/qualificacoes/edit.html.erb
<h1>Editing qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacoes_path %>

ruby/vota_prato/app/views/qualificacoes/index.html.erb
<h1>Listing qualificacoes</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
    <td><%= link_to 'Show', qualificacao %></td>
    <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Destroy', qualificacao, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qualificacao', new_qualificacao_path %>

ruby/vota_prato/app/views/qualificacoes/new.html.erb
<h1>New qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', qualificacoes_path %>

ruby/vota_prato/app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>


<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>