ruby/vota_prato/config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :restaurantes

  resources :qualificacoes

  resources :clientes

   match 'rack', :to => proc{|env|[200,{"Content-Type" => "text/html"},["App Rack numa rota Rails"]]}	
   match ':controller(/:action(/:id(.:format)))'
end

ruby/vota_prato/app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :comentavel_id, :comentavel_type, :conteudo

	belongs_to :comentavel,
			:polymorphic => true
end

ruby/vota_prato/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render json: @comentario, status: :created, location: @comentario }
      else
        format.html { render action: "new" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
	puts 'ENTREIiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii'	
	@comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to(comentarios_url) }
      format.xml  { head :ok }
	  format.js   { head :ok }
    end
  end
end

ruby/vota_prato/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

ruby/vota_prato/app/views/comentarios/_comentario.html.erb
<div id="comentario_<%= comentario.id %>">
	<%= comentario.conteudo %>
	<%= link_to image_tag("delete.png"), comentario , 
		:remote => true , 
		:method => :delete,
		:id => "remove_comentario_#{comentario.id}" %>
</div>
<%=content_for :js do%>
  $('#remove_comentario_<%=comentario.id%>').bind('ajax:success',
        function(xhr,result){
          $('#comentario_<%=comentario.id%>').remove();
        }
	);
<%end%>

ruby/vota_prato/app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :comentavel_id %><br />
    <%= f.number_field :comentavel_id %>
  </div>
  <div class="field">
    <%= f.label :comentavel_type %><br />
    <%= f.text_field :comentavel_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/vota_prato/app/views/comentarios/_novo_comentario.html.erb
<div id='novo_comentario'>
  <a href="#" onclick="$('#novo_comentario').children().toggle();">Novo comentario</a>

  <div id="form_comentario" style="display: none;">

    <%= form_for Comentario.new, :remote => true do |f| %>
      <%= hidden_field :comentario, :comentavel_id, :value => comentavel.id %>
      <%= hidden_field :comentario, :comentavel_type, :value => comentavel.class %>

      <div class="field">
        <%= f.label 'conteudo' %><br />
        <%= f.text_area 'conteudo' %>
      </div>

      <div class="actions">
        <%= f.submit %>
        <a href="#" onclick="$('#novo_comentario').children().toggle();">Cancelar</a>
      </div>

    <% end %>
  </div>
</div>

<%content_for :js do%>
 $('#form_comentario').bind('ajax:complete', function(xhr, result){
   $('.comentario').html(result.responseText);
   $('#form_comentario textarea').val("")
   $('#form_comentario').hide();
   $('#novo_comentario > a').show();
 });
<%end%>

ruby/vota_prato/app/views/comentarios/create.js.erb
<b>Comentarios:</b>
<%= render(:partial => "comentarios/comentario",
           :collection => @comentario.comentavel.comentarios) %>

ruby/vota_prato/app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

ruby/vota_prato/app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Conteudo</th>
    <th>Comentavel</th>
    <th>Comentavel type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.conteudo %></td>
    <td><%= comentario.comentavel_id %></td>
    <td><%= comentario.comentavel_type %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

ruby/vota_prato/app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

ruby/vota_prato/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conteudo:</b>
  <%= @comentario.conteudo %>
</p>

<p>
  <b>Comentavel:</b>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <b>Comentavel type:</b>
  <%= @comentario.comentavel_type %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>