ruby/vota_prato/config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :restaurantes

  resources :qualificacoes

  resources :clientes

   match 'rack', :to => proc{|env|[200,{"Content-Type" => "text/html"},["App Rack numa rota Rails"]]}	
   match ':controller(/:action(/:id(.:format)))'
end

ruby/vota_prato/app/models/cliente.rb
#encoding: UTF-8

class Cliente < ActiveRecord::Base
	attr_accessible :nome, :idade
	
	has_many :qualificacoes
	
	
	validates_presence_of :nome, :message => " - deve ser preenchido"
	validates_uniqueness_of :nome, :message => " - deve ser unico"
	
	validates_numericality_of 	:idade, 
								:greater_than=>0, 
								:less_than=>100, 
								:message => "ninguém é tão velho"
	
end

ruby/vota_prato/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully created.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end
end

ruby/vota_prato/app/helpers/clientes_helper.rb
module ClientesHelper
end

ruby/vota_prato/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.text_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/vota_prato/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

ruby/vota_prato/app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Idade</th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.idade %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

ruby/vota_prato/app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

ruby/vota_prato/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Idade:</b>
  <%= @cliente.idade %>
</p>

<%= link_to 'Nova qualificação', :controller => 'qualificacoes',
                                :action => 'new',
                                :cliente => @cliente %>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>