ruby/vota_prato/config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :restaurantes

  resources :qualificacoes

  resources :clientes

   match 'rack', :to => proc{|env|[200,{"Content-Type" => "text/html"},["App Rack numa rota Rails"]]}	
   match ':controller(/:action(/:id(.:format)))'
end

ruby/vota_prato/app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
	attr_accessible :nome, :endereco, :especialidade

	has_many :qualificacoes
	has_many :comentarios,	
			 :as => "comentavel"

	has_and_belongs_to_many :pratos
	
	
	
	scope :massas, where({ :especialidade => 'Massas' })
	scope :recentes, where(["created_at >= ?", 2.months.ago]);
	
	
	validates_uniqueness_of :nome, :message=> "nome ja cadastrado"
	validates_uniqueness_of :endereco, :message=> "endereco ja cadastrado"
	validates_presence_of :nome, :message=> "deve ser preenchido"
	validates_presence_of :endereco, :message=> "deve ser preenchido"
	validates_presence_of :especialidade, :message=> "deve ser preenchido"
	
	
	
	validate :primeira_letra_deve_ser_maiuscula
	
	
	
	private
	def primeira_letra_deve_ser_maiuscula
	
		errors.add("nome","primeira letra deve ser maiuscula") unless nome =~ /[A-Z].*/
		
	end
	
	
	
	
	
	
	
end

ruby/vota_prato/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
	def index
		@restaurantes = Restaurante.order("nome").paginate :page => params['page'], :per_page=>5
	end
	def new
		@restaurante = Restaurante.new
	end 
	def create
		@restaurante = Restaurante.new(params[:restaurante])
		if (@restaurante.save)
			redirect_to :action => "show", :id => @restaurante
		else
			render :action => "new"
		end	
	end
	def edit
		@restaurante = Restaurante.find(params[:id])
	end
	def update
		@restaurante = Restaurante.find(params[:id])
		if (@restaurante.update_attributes(params[:restaurante]))
			redirect_to :action => "show", :id => @restaurante
		else
			render :action => "edit"
		end	
	end
	def show
		@restaurante = Restaurante.find(params[:id])
	end
	def destroy
		@restaurante = Restaurante.find(params[:id])
		@restaurante.destroy
		redirect_to :action => "index"
	end
end

ruby/vota_prato/app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

ruby/vota_prato/app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :especialidade %><br />
    <%= f.text_field :especialidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/vota_prato/app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

ruby/vota_prato/app/views/restaurantes/index.html.erb
<h1>Listing restaurantes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Especialidade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurantes.each do |restaurante| %>
  <tr>
    <td><%= restaurante.nome %></td>
    <td><%= restaurante.endereco %></td>
    <td><%= restaurante.especialidade %></td>
    <td><%= link_to 'Show', restaurante %></td>
    <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @restaurantes %>

<br />

<%= link_to 'New Restaurante', new_restaurante_path %>

ruby/vota_prato/app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurantes_path %>

ruby/vota_prato/app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @restaurante.nome %>
</p>

<p>
  <b>Endereco:</b>
  <%= @restaurante.endereco %>
</p>

<p>
  <b>Especialidade:</b>
  <%= @restaurante.especialidade %>
</p>


<%= comentarios @restaurante %>

<%= novo_comentario @restaurante %>


<b>Nota média: </b><%= @restaurante.qualificacoes.average(:nota) %><br/>
<b>Qualificações: </b><%= @restaurante.qualificacoes.count %><br/>
<b>Preço médio: </b><%= @restaurante.qualificacoes.average(:valor_gasto) %><br/><br/>

<%= link_to "Qualificar este restaurante", :controller => "qualificacoes",
                                           :action => "new",
                                           :restaurante => @restaurante %>


<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>